"""add users table

Revision ID: 31a1e5f26389
Revises: cdf301ecf35d
Create Date: 2020-07-05 16:37:32.401003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a1e5f26389'
down_revision = 'cdf301ecf35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chinesebody', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('imgossdir', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('oggossdir', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('oggossdir')
        batch_op.drop_column('imgossdir')
        batch_op.drop_column('chinesebody')

    # ### end Alembic commands ###
