"""add users table

Revision ID: 63c9b6a1b57e
Revises: 31a1e5f26389
Create Date: 2020-07-07 15:34:28.615288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c9b6a1b57e'
down_revision = '31a1e5f26389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagname', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###
