"""add users table

Revision ID: 6eff8c01910a
Revises: c94ef26b66eb
Create Date: 2020-07-11 16:22:11.593353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eff8c01910a'
down_revision = 'c94ef26b66eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wordname', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_words'))
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_timestamp'), ['timestamp'], unique=False)

    op.create_table('posts_words',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_posts_words_post_id_posts')),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('fk_posts_words_word_id_words'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_words')
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_timestamp'))

    op.drop_table('words')
    # ### end Alembic commands ###
