"""add users table

Revision ID: c94ef26b66eb
Revises: 90b40fa13351
Create Date: 2020-07-10 14:49:35.823607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94ef26b66eb'
down_revision = '90b40fa13351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oggossdir', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('oggossdir')

    # ### end Alembic commands ###
